[package]
name = "url-trans"
version = "0.1.0"
edition = "2021"

[dependencies]
url = "2.5.4"
headless_chrome = { version = "1.0.15", features = ["fetch"] }
reqwest = { version = "0.12", features = ["json", "blocking"] }
lazy-regex = "3.4.1"
